version: '3.7'

services:
  database:
    image: postgres
    container_name: database_day_planner_360
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jsnulvonmktoqbtb
      - POSTGRES_DB=day_planner_360_db
    volumes:
      - .:/data/postgres
  app:
    build: .
    container_name: day_planner_360_app
    env_file:
      - .env
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'placeholder@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'fakepassword123!'
    ports:
      - '16543:80'
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
